### ISSUE TITLE
Digest editorial reordering

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#1103]
## I expect
@LPardue WDYT about this roadmap? I'd address each one in a separate PR.
If you agree, I can cherry-pick the first ones from your PR so you won't have to do it twice :)

Digest Headers to be reordered:

- [x] move the "deprecated algorithms" security consideration directly in {{digest-agorithms}} #1109
- [x] merge the {{digest-algorithm-encoding-examples}} in its parent section {{representation-digest}} #1110
- [x] move Digest Header and Want-Digest header outside Header Field Specifications #1111 #1116
- [x] move {{representation-digest}} under {{digest-header}} #1117
- [x] move {{digest-algorithms}} down #1112
- [x] move {{resource-representation}} examples to Annex B #1122 
- [ ] ensure people start reading from  {{representation-digest}} #1123 
- [ ] refactor Digest to be more direct #1124 

Optional:

- [ ] integrate examples from #1091 into {{resource representation}}

**Comment by LPardue** [comment]
That sounds like a good plan, thanks. Please action it and I'll review promptly.

This is a set of editorial changes that I think would add value to the specification readability. My jumbo PR (#1091) had some problems, so lets focus on landing the easy-to-agree items and not try to rush everything through before the submission deadline if we are uncomfortable. We can continue working on the thornier editorials even after the submission deadline.

**Comment by ioggstream** [comment]
Here's a first bunch of PRs. PTAL :) thanks for all the support!

**Comment by ioggstream** [comment]
@LPardue I'm trying to refactor and I have this proposal:

https://httpwg.org/http-extensions/ioggstream-1103-test/draft-ietf-httpbis-digest-headers.html

we need rewording but just look at the sections ordering and let me know

**Comment by LPardue** [comment]
This section outline looks good. I approved, #1122 so let merge it. What's next?

**Comment by ioggstream** [comment]
> This section outline looks good. I approved, #1122 so let's merge it. What's next?

Now we have #1123 and #1124 which should end the refactoring.

**Comment by LPardue** [comment]
All the PRs look good, even the optional one. Thanks for your work on this.

Let's get them merged, then take a once-over review to catch any basic errors that might have crept in. Then one of us can cut the release.
