### ISSUE TITLE
Digest editorial refresh before WGLC

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#1250]
## Tasks

- [x] algorithm registration #1533 
- [x] digest-algorithm lowercase #1253 
- [x] deprecate parameters and wait for feedback :) #1259 @LPardue 
- [x] Algorithm agility #1284 
- [x] sha-1 deprecated o obsoleted? #1292 
- [x] detail encrypted quirks eg with content-coding #1285 
- [x] clean up Representation Digest https://github.com/httpwg/http-extensions/pull/937#discussion_r472018411
- [x] remove reference to "validator fields" if they are not used anymore
- [x] consistent usage of backticks #1255 

```
`Digest` vs Digest vs "Digest"
`digest-algorithms` vs digest-algoritms vs "digest-algorithms"
```

- [x] consistent usage of "-" #1256  

```
digest-algorithms vs digest algorithms

```

- [x] consistent usage of lowercase digest-algorithms with double quote "sha-256" in text #1255

- [x] close #1139 and #1138  about old algorithms unless somebody comes with a proposal. @LPardue

**Comment by ioggstream** [comment]
@LPardue do you have any news on #1139 and #1138 about old algorithms?

**Comment by LPardue** [comment]
I'll propose some new text shortly

**Comment by ioggstream** [comment]
* Abstract: 'thus' reads oddly; try a different word?
* [x] Abstract: It's sufficient to say that this document obsoletes 3230; you don't need to go into why in the abstract.
* [x] 1. Introduction: 'core' is an informal term; recommend just "HTTP does not define...", or dropping the first sentence.
* [x] 1. Introduction: Use of 'resource' is incorrect; I think you're looking for 'representation' (throughout). I.e., it is meaningless to say that you protect the integrity of a resource, because a resource is an ephemeral concept.
* [ ] 1. Introduction: Second sentence of second para is very long, and very passive.
* [x] 1. Introduction: 'representation-data' should drop the hyphen.

**Comment by ioggstream** [comment]
[ ] * 1. Introduction: Typically, the introduction contains a 'map' to the rest of the specification, laying out the logical progression of concepts introduced. I can see that 1.2. does that partially, but it needs to be completed and up-front.
[ ] * 1.1. Is this section necessary? If so, is it necessary for it to be a separate section?
[x] * 1.2. 'This Proposal' is a very odd name for a specification section
[x] * 1.2. The first para is difficult to read; suggest starting with 'This document updates the...'
[x] * 1.2. Use of eg. isn't appropriate; spell out 'for example'
[x] * 1.3. proposal -> specification (or document)
* 1.3. Can we move from lists to prose here, or at least a single type of list?

See https://github.com/httpwg/http-extensions/pull/new/ioggstream-mark-review-3

**Comment by ioggstream** [comment]
- [x] * 3. It's probably worth mentioning that they're comma-separated in prose.
- [ ] * 3. I'm uncomfortable with relying on examples to specify how this spec works normatively; by their nature, examples are not 'comprehensive.' While this spec shouldn't re-specify HTTP, the header's definition should be clear enough that a reader doesn't have to dig around in the examples and other specs to understand what's going on.
- [x] * 3. Disagreeing plurals in 'an incremental digest-algorithms'.
- [x] * 4. Is Want-Digest a request field, a response field, or both? In either or both cases, what's the scope of the assertion?
- [x] * 4. A reference to SEMANTICS 12.4.2 is necessary.

**Comment by ioggstream** [comment]
- [x] * 5. I think you should come out and say that digest-algorithm values MUST be compared in a case-insensitive fashion.
- [ ]  Also, is the entire value case-insensitive, or just the token identifying the value?
- [x]  5. 'The IANA acts a registry' reads oddly; it maintains the registry. Also, saying 'the registry contains the tokens listed below' is misleading; these are initial registrations, which can be modified and added to after the RFC is published.
- [ ]  Also, these might be better placed in IANA Considerations.
- [x] * 5. There should not be RFC2219-MUSTs in IANA registry text. 
- [ ] This can be addressed by having a requirement similar to "Deprecated digest algorithms MUST NOT be used."
- [ ] * 5. The ability to have a digest algorithm that ignores content-codings is something of a surprise after reading section 2; it needs to be at least mentioned up there.

**Comment by ioggstream** [comment]
All issues closed.
