### ISSUE TITLE
TSVART review - editorial comments

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#1802]
Comments from Bob Briscoe's review:

General (all sections).

- [x]  E#0a) Are precedence and priority interchangeable with urgency?

It's called a priority field, and the parameter is called urgency, but
sometimes the term priority or precedence is used to describe urgency. Please
go through the draft using priority or urgency consistently, and remove
precedence unless it's there for good reason.

§1. Introduction

- [ ] E#1a) The "For example" in para 2 is actually the general point not the
example, whereas the example is in the previous para.

- [x] E#1b) The last para "   The prioritization scheme and priority signals defined
herein can act as a substitute for RFC 7540 stream priority." would fit better
3 paras earlier, just after "HTTP/2 [HTTP2] has consequently deprecated the use
of these stream priority signals."

- [ ] E#1c) It would help to state what the interaction model is for the priority
field. I believe it's not as simple as just "e2e" (see technical comment
earlier about §5). Although I've suggested that normative text about this ought
to be in the §5, it needs to be stated early on (probably in the intro, not
just the abstract), because the reader needs it to understand §§2 & 4.

§1.1.  Notational Conventions

- [ ] E#1d) Was HTTP/2 priority only from C-S?

   The term HTTP/2 priority signal is used to describe the priority
   information sent from clients to servers in HTTP/2 frames;

Neither RFC7540 nor the http2bis draft says that an HTTP/2 priority signal
cannot be sent by a server. It may be that this was the unstated intention but,
if it wasn't, the above sentence is incorrect.

§2.  Motivation for Replacing RFC 7540 Priorities

- [x] E#2a) Not just absence

CURRENT:

   compatibility (see Section 5.3.2 of [HTTP2]), which means that they
   might still be used in the absence of alternative signaling, such as
   the scheme this document describes.

PROPOSED:

   compatibility (see Section 5.3.2 of [HTTP2]), because they
   might still be used by other nodes.

REASONING:
7540 priority fields are not only used in the absence of alternative
signalling. They are used by the client in parallel to extensible priorities
before it receives the server's SETTINGS frame.

2.1.1. Advice when Using Extensible Priorities as the Alternative

- [ ] E#2b)
CURRENT:

   might be useful to nodes behind the server that the client is
   directly connected to.

PROPOSED:

   might be useful to a server behind the directly connected node.

REASONING:
Removes ambiguity - I initially read this as "nodes (behind the server) that"
rather than "...the server that".

§3.  Applicability of the Extensible Priority Scheme

- [x] E#3a)

   The priority scheme defined by this document considers only the
   prioritization of HTTP messages and tunnels, see Section 9,
   Section 10, and Section 11.

Is this sentence meant to be as mysterious as it sounds? If this document only
considers messages and tunnels, what else doesn't it consider? Is 'HTTP
messages' deliberately used instead of 'HTTP responses'? If it is wider than
just responses, then all the places in the draft where it says it is about http
responses need to be generalized (e.g. §4.1, §4.2, §8, §10 §14). But will this
make the draft so abstract that it becomes incomprehensible? Perhaps better to
explain here that it is applicable to a few other odd messages and tunnels, but
it is primarily about responses, so where the draft talks about responses, it
is not intended to preclude the other less-common cases.

It's not clear what the references to §§9,10,11 are there for. Are they further
info about tunnels (only §10 has one sentence on tunnels)? Or are they meant to
list all the sections about scheduling things? if so, why not also §12 on
scheduling retransmissions?

- [x] E#3b)
CURRENT:

   they can also define how this priority scheme
   can be applied.

PROPOSED:

   they can also define how the present priority scheme
   can be extended to support the new extension.

RATIONALE:
I think this is what was intended?

§4.  Priority Parameters

- [x] E#4a) First use of reprioritize
Ought to explain long-hand why reprioritization might be needed here, given it
hasn't been mentioned yet.

- [x] E#4b)

   Note that handling of omitted parameters is different
   when processing an HTTP response

When what processes an HTTP response? The client? An intermediary? Both?

§4.1. Urgency
- [x] E#4c)

   integer between 0 and 7, in
   descending order of priority

   The smaller
   the value, the higher the precedence.

Suggest the latter is moved up 2 paras.
(BTW, what possessed anyone to define this in the most illogical way possible?
So that the highest numerical urgency means the lowest urgency?)

- [x] E#4d) Priority = Precedence = Urgency?
This section interchanges the words 'priority', 'precedence' and 'urgency'. Why
not just use urgency throughout? Otherwise you have to define that priority and
precedence mean exactly the same as urgency.

§4.3.  Defining New Parameters

- [x] E#4e) Not new parameters for everything

Suggested replacement section heading: "Defining New Priority Parameters"

s/   When attempting to define new parameters,/
 /   When attempting to define new priority parameters,/

§4.3.1.  Registration

- [x] E#4f)

s/in Structured Fields Dictionary/
 /in the Structured Fields Dictionary

§5.  The Priority HTTP Header Field

- [x] E#5a)

s/carries priority parameters Section 4./
 /carries priority parameters (Section 4)./

- [x] E#5b)

s/As is the ordinary case for HTTP caching [CACHING], a response with a
  Priority header field might be cached /
 /A response with a Priority header field might be cached [CACHING]/

§7.  The PRIORITY_UPDATE Frame
- [x] E#7a)

s/which can can be bound by/
 /which can can be bounded by/

(Oxford dictionary example '‘the ground was bounded by a main road on one side
and a meadow on the other’')

§8.  Merging Client- and Server-Driven Parameters

- [ ] E#8a)
First para: The 2nd example isn't a particularly good example of 'server knows
best'; it even admits that it's the visual-ness of the client that determines
the priority.

- [x] #8b) What is 'the logic being defined' meant to mean?

s/This is different from the logic being defined for the request header field,/
 /This is different from the approach for the request header field,/

Perhaps?

§10.  Server Scheduling

- [x] E#10a) No guidance is provided,... except for a page and a half

   No guidance is provided about how this can or
   should be done.  ...
   For these reasons, ... this document only provides some basic
   recommendations for implementations.

(Contradictory.)
It seems like the rather over-negative caveats in the first 3 paras need to be
revisited now that the page and a half of recommendations (some normative) has
been added after them.

§10.1.  Intermediaries with Multiple Backend Connections

- [x] E#10b)
s/inflight/in flight/

§11.  Scheduling and the CONNECT Method

- [x] #E11a)

   A
   client that issues multiple CONNECT requests can set the incremental
   parameter to true, servers that implement the recommendation in
   Section 10 will schedule these fairly.

s/...true, servers.../
 /...true. Servers.../

There are 3 recommendations in §10. Which one?

Given §10 starts with a load of caveats about how hard this stuff is to get
right, is it appropriate to assert with such certainty that scheduling will be
fair?

§12.  Retransmission Scheduling

- [x] E#12a)

s/Section 6.2.4 of [QUIC-RECOVERY], also highlights/
 /Section 6.2.4 of [QUIC-RECOVERY] also highlights/

§13.1.  Coalescing Intermediaries

- [x] E#13a)

   It is sometimes beneficial for the server running behind an
   intermediary to obey to the value of the Priority header field.

This seems an odd sentence to have in this draft. I think it is meant to be in
the context of the previous sentence about coalesced requests with priorities
set by different clients. Needs rewriting, I think.

s/obey to/
 /obey/

s/the Priority header field/
 /each Priority header field/

s/as another signal in its prioritization decisions./
 /as another input in its prioritization decisions./

§14.  Why use an End-to-End Header Field?

- [x] E#14a)

s|Contrary to the prioritization scheme of HTTP/2|
 |In contrast to the prioritization scheme of HTTP/2|

Contrary in this form has an implication that HTTP/2 was wrong. That might be
intended. But 'in contrast to' has less of a 'know-it-all' feel.

- [x] E#14b) Answering a different question

   rather
   than how relatively urgent each response is to others.

This seems to be a (weak) rationale for relative rather than absolute
priorities, whereas the section heading promises the rationale for an e2e
header. I suggest the whole first sentence of this 2nd para is deleted, because
the next sentence gives a sufficient rationale.

- [x] E#14c) Answering another different question

   It should also be noted that the use of a header field carrying a
   textual value makes the prioritization scheme extensible; see the
   discussion below.

This is also not a rationale for an e2e header. Perhaps it belongs in the Intro?

Alternatively, the section title could be changed to "Rationale for Priority
Protocol Design" or something. Then it could give rationale for absolute
priority values and textual values as well as e2e header fields.

- [x] E14d) see what "discussion below"?

Perhaps this refers to the sentence in Security Considerations that refers to
[STRUCTURED FIELDS]? If so, it's hardly a "discussion".

§16.  IANA Considerations

- [x] E#16a)

   populate it with the
   types defined in Section 4; see Section 4.3.1 for its associated
   procedures.

I suspect IANA will prefer the exact text they should use to be written here.

**Comment by LPardue** [comment]
We've been working through these editorial issues with the various associated PRs. To help track progress, here is the current (at the time of writing) status of open items on the issue based on my take:

* Precedence, Priority, Urgency (E#0a, E#4c, E#4d)
  * Further discussion needed
  
* E#1a
  *  Since this priority scheme is for HTTP in general, anything the refers to HTML is only an example of how the scheme applies. Not seeing any action required here.
  
* E#1c
  * The Priority header field is a signal. How it is used by clients, servers and intermediaries is described in the intro. That text was added in response to WGLC. I don't feel that expanding the text here as suggested would improve the document because it relies on text elsewhere in the document to understand all the details.

* E#1d
  * RFC7540 server-to-client signals seem like something that was technically allowed but never used by anyone in practice. There is a 7540bis activity underway, I raise an issue for this https://github.com/httpwg/http2-spec/issues/1000. With respect to this document, we are defining our own terms for the benefit of this document. The term is consistently applied in the document with this in mind. I'm happy keeping things as is.
  
* E#2b
  * The current text is accurate. The header might be useful to nodes behind the server (imagine a front-end HTTP server that talks to some other process via CGI etc)

* E#3a
  * Agreed. See https://github.com/httpwg/http-extensions/pull/1806 for changes to address this.
  
* E#3b
  * The intent here is that "things we don't know about" might or might not be able to apply this scheme. Take for example HTTP/3 datagrams - we can't say that they just need to extend the scheme (they might not!) and we can't assume the scheme will work for them (otherwise we'd have to write some scheduling considerations). So the responsibility is on the extensions to state how they think they fit with this scheme. The text has changed a bit in https://github.com/httpwg/http-extensions/pull/1806 (targetted for E#3b) but the intent remains the same.

* E#4a
  * See https://github.com/httpwg/http-extensions/pull/1812

* E#5b
  * See  https://github.com/httpwg/http-extensions/pull/1815

* E#8a
  * This example seems fine to me. An operator could know that the font will block text rendering and want to prioritize that for web page performance or QoE reasons.

* E#11a
  * See https://github.com/httpwg/http-extensions/pull/1816

**Comment by LPardue** [comment]
closing this now that we addressed the items we decided to. Any remaining open tasks are to be left without action.
