### ISSUE TITLE
Mention effects of transfer coding and HTTP trailers

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#884]
## Suggestion

Mention `digest` usage with `Transfer-Encoding` and trailers

 * [x] use with transfer coding should not affect `digest` because transfer coding is not a property of the representation;
 * [ ] use with multiple transfer codings (eg with intermediaries?) should not affect `digest` too; (see above)
 * [x] caveats with transfer codings, trailers #884  and signatures (this may be addressed in digest+signatures BCP);

## Considerations

- [x] sending `digest` in HTTP trailers may help the sender in dinamically calculating `digest-value`
  while streaming content; #1157 
- this only work if it's the Origin-Server to apply the `Transfer-Coding`;
- [x] this may not work for all  `digest-algorithms`, eg. see [mi-sha256 in MICE I-D](https://github.com/martinthomson/http-mice/blob/master/draft-thomson-http-mice.md) for a counter-example); @martinthomson @jyasskin  #1157 
- a clarification on using `Digest` with `Transfer-Encoding` should be added before adding this;
- [x] Digest in trailer MUST NOT be discarded #1157

## Notes

- Suggested in https://lists.w3.org/Archives/Public/ietf-http-wg/2019JulSep/0087.html
- being transfer coding a representation manipulation assimilated in this spec to range-requests  co, we provided the following examples #884

**Comment by ioggstream** [comment]
### Example: http/2 trailers

```
Request:

 :method = GET
 :scheme = https
 :path = /resource
 CONTINUATION
 te: trailers
 want-digest: sha-256

Response:

  :status =200
  CONTINUATION
  trailer: digest
  DATA
  {"hello": "world"}
  HEADERS
  digest: sha-256=fafafa...

```

**Comment by jyasskin** [comment]
When thinking about sending the digest in trailers, look at which use cases from #872 can actually take advantage of that.

**Comment by LPardue** [comment]
What work is remaining to close out this issue?
